#!/bin/sh

BLANK='#000000'  # Black background
CLEAR='#ffffff22'
DEFAULT='#9b59b6'  # Purple ring color
TEXT='#9b59b6'  # Purple text color
WRONG='#880000bb'
VERIFYING='#00564dE6'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$DEFAULT     \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 9                     \
--clock                      \
--indicator                  \
--date-str="%A, %Y-%m-%d"    \
--date-str="%A, %Y-%m-%d"    \
--keylayout 1                \
